### PR TITLE
feat!(hyprcursor): implement nominal_size metadata

### PR DESCRIPTION
**Pull request by Covkie**
requires hyprcursor at least 0.1.11

This will fix users having to set multiple sizes on hyprland

see hyprwm/hyprcursor/pull/73

With this merge https://github.com/catppuccin/cursors/issues/31#issuecomment-2543179142 & https://github.com/catppuccin/cursors/pull/55#issuecomment-2502527484 don't apply anymore and users can set one size and expect them to apply at the same scale.

### CODE REVIEW

**Review by sgoudham — COMMENTED** [review]
Is this technically a breaking change?

**Comment by sgoudham** [comment]
Sure, that'd be appreciated.

A breaking change is anything that will cause the user to change their settings so I'm wondering if merging this will default their cursor to a different size to what the current release has, in which case we should definitely ship this as a breaking change.

**Comment by izmyname** [comment]
> Ah yeah then its def a breaking change. (Even though its 'technically' more correct :p)

I believe, an average Hyprland user will be able to figure out - why the cursor got bigger and change its size.

**Comment by sgoudham** [comment]
> I believe, an average Hyprland user will be able to figure out - why the cursor got bigger and change its size.

Sure, but that won't change us shipping it as a breaking change 👍

**Review by sgoudham — APPROVED** [review]

**Pull request merged**
